openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Todo App REST API
servers:
  - url: http://localhost:3000/
paths:
  /items:
    get:
      summary: Получение списка дел
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    completed:
                      type: boolean
    post:
      summary: Добавление нового дела
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: "OK"
  /items/{id}:
    delete:
      summary: Удаление дела по id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
    put:
      summary: Обновление дела по id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                completed:
                  type: boolean
      responses:
        "200":
          description: "OK"
